name: Deploy MkDocs
on:
  push:
    branches: 
      - main  # or master, depending on your default branch name
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - name: Deploy
        run: mkdocs gh-deploy --force
